version: "3.9"

services:
  app:
    build: .
    container_name: crowdfunder_app
    ports:
      - "1010:1010"
    env_file:
      - .env.dev
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo:7
    container_name: crowdfunder_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: